@host=https://localhost:7047

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Doe",
    "Email": "john@mantinband.com",
    "Password": "Amiko1234!!"
}