@host=https://localhost:7047
@userId=d110bcd4-0cdb-4f93-9b3c-0d03cc84e656

### Admin
POST {{host}}/users/{{userId}}/profiles/admin

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer

### Participant
POST {{host}}/users/{{userId}}/profiles/participant