@host=https://localhost:7047
@adminId=2150E333-8FDC-42A3-9474-1A3956D46DE8

POST {{host}}/api/Subscriptions
Content-Type: application/json

{
    "subscriptionType": "Free",
    "adminId": "{{adminId}}"
}
