@host=https://localhost:7047
@adminId=9f351e6c-cdd0-4c0f-86a2-ec9bb06e6475

POST {{host}}/api/Subscriptions
Content-Type: application/json

{
    "subscriptionType": "Free",
    "adminId": "{{adminId}}"
}
