@host=http://localhost:5238
@adminId=5f3b3b7b-5b9a-4b9e-9b0a-9f0b0b0b0b0b

POST {{host}}/api/Subscriptions
Content-Type: application/json

{
    "subscriptionType": "Free",
    "adminId": "{{adminId}}"
}